### PR TITLE
allow different UID types

### PR DESCRIPTION
**Pull request by jmmshn**
## Only allow UUIDs that can be sorted in time

Partially addresses:
https://github.com/materialsproject/jobflow/issues/519

- Change all the function names  `*uuid` -> `*uid`
- Added new setting for `UID_TYPE`
- Added support for `uuid1` and `ulid` via `python-ulid`
- Added functions to retrieve time stamp information
- Added tests

### CODE REVIEW

**Comment by gpetretto** [comment]
Thanks for implementing the change and making uuid4 the default. 
It would be convenient for me (and maybe for others), not to have an abrupt change in the exposed functions as I am using the `suuid` function to generate a string uuid in a few places. It is not such a big deal, but would it be fine to keep the `suuid` function in the `uuid` module with a deprecation warning?

**Comment by jmmshn** [comment]
Yeah that makes sense.

**Comment by jmmshn** [comment]
BTW does anyone know what the `s` in `suuid` stands for?

**Comment by utf** [comment]
Thanks @jmmshn.

Is it possible to make `ulid` an optional dependency and only import it if the user has asked for it in their settings file. The code should also throw an appropriate error explaining which python package is needed to use `ulid` if it is not installed.

**Comment by utf** [comment]
Thanks @jmmshn

**Comment by jmmshn** [comment]
BTW, can we get a release with this, then I can finish the atomate2 PR.

**Comment by utf** [comment]
Done (`v0.1.17`)

**Pull request merged**
