### PR TITLE
add s3store yaml parsing

### PR DESCRIPTION
**Pull request by jmmshn**
## Fixed parsing of nested stores (Ex. S3Store)
Now checks the `dict_spec` for the word "type" and recursively calls the constructor.

### CODE REVIEW

**Comment by utf** [comment]
Please could you also add an example of this format in the JobflowSettings: https://github.com/materialsproject/jobflow/blob/45eb719f5aec3dab1aaf47b2034069186c6d1069/src/jobflow/settings.py#L44-L58

**Comment by jmmshn** [comment]
Ok ready to merge

**Comment by utf** [comment]
Error is unrelated to this PR: https://github.com/jupyter/nbconvert/issues/1736

**Comment by utf** [comment]
Thanks!

**Pull request merged**
