### PR TITLE
Add dynamic option to append_name

### PR DESCRIPTION
**Pull request by JaGeo**
Hi @utf , @davidwaroquiers ,

I have made a draft implementation to address #639 . Let me know what you think. I hope I haven't overlooked anything.

### CODE REVIEW

**Comment by JaGeo** [comment]
I am working on https://github.com/materialsproject/atomate2/pull/752. To finish it, this or a similar functionality would  be needed. Otherwise, `mock_vasp` does not work.

**Comment by davidwaroquiers** [comment]
Hi @JaGeo 

I did not test but I think it should work. I guess for your own needs is fine but if I have to say one thing, maybe I would make a new update_name method that has more functionalities:

- Update the name without adding prefix/suffix (this is already available if you just do some_job.name = 'mynewname', but not in a dynamic way)
- Filters similar to update_metadata and others

API of this method could be:

```
def update_metadata(
        self,
        newname: str | None = None,
        prefix: str | None = None,
        suffix: str | None = None,
        name_filter: str = None,
        function_filter: Callable = None,
        dynamic: bool = True,
    ):
```

Then the append_name can just be used by this method if prefix and/or suffix is provided. (and the dynamic in append_name is not needed, I guess it would be better/less confusing if it is only in one place)

Not sure if it is absolutely essential, but it would make thing consistent with the rest of the update_* methods. (and I guess it would not be a huge work but again, it's all a matter of "is it needed and worth it if there is no use case right now ?")

**Comment by JaGeo** [comment]
I don't really have a use case for the other cases. My use case currently to make sure I can differentiate jobs for moch_vasp.

(And, yes, it works. I tested it 😅)

**Comment by utf** [comment]
Thanks, @JaGeo. I'll merge this for now. I put @davidwaroquiers comment into a new issue #648.

**Comment by JaGeo** [comment]
Thanks, @utf . Would a new version be okay? Then, I can finalize the Grüneise workflow in atomate2 as well

**Comment by utf** [comment]
I just pushed a new version (v0.1.18). It should be out soon.

**Comment by JaGeo** [comment]
Thank you @utf !

**Pull request merged**
